name: Build MemcardRex

on: 
  push:
    branches:
      - master

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v1
          with:
            fetch-depth: 0
        - name: Generate build number
          id: buildnumber
          uses: einaregilsson/build-number@v3
          with:
            token: ${{secrets.github_token}}  
        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            tags: latest
            build-args: |
              BUILD_NET=1.0.0.${{steps.buildnumber.outputs.build_number}}
        - uses: shrink/actions-docker-extract@v1
          id: extract
          with:
            image: docker.io/library/latest
            path: tmp/.
        - name: Upload Dist
          uses: actions/upload-artifact@v2
          with:
            path: ${{ steps.extract.outputs.destination }}
            name: dist
