name: Build MemcardRex

on: 
  push:
    branches:
      - master

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v1
          with:
            fetch-depth: 0
        - name: Generate build number
          id: buildnumber
          uses: einaregilsson/build-number@v3
          with:
            token: ${{secrets.github_token}}  
        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            tags: latest
            build-args: |
              BUILD_NET=1.0.0.${{steps.buildnumber.outputs.build_number}}
        - uses: shrink/actions-docker-extract@v1
          id: extract
          with:
            image: docker.io/library/latest
            path: dist/.
        - name: Upload Dist
          uses: actions/upload-artifact@v2
          with:
            path: ${{ steps.extract.outputs.destination }}
            name: dist
        - name: Create Draft Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: 1.0.0.${{steps.buildnumber.outputs.build_number}}
            release_name: Release 1.0.0.${{steps.buildnumber.outputs.build_number}}
            draft: true
            prerelease: false
        - uses: actions/upload-release-asset@v1.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ steps.extract.outputs.destination }}/MemcardRex.dmg
            asset_name: MemcardRex.dmg
            asset_content_type: application/octet-stream
        - uses: actions/upload-release-asset@v1.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ steps.extract.outputs.destination }}/MemcardRex.msi
            asset_name: MemcardRex.msi
            asset_content_type: application/octet-stream
        - uses: eregon/publish-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release_id: ${{ steps.create_release.outputs.id }}
